### ISSUE TITLE
Ctrl+Shift+Enter for creating a text block

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#102]
#100 added 2 new keyboard shortcuts: 

- Ctrl+Enter: Executing code
- Shift+Enter: Executing and focus on next block. If last block then create a new code block.

Ctrl+Shift+Enter should behave like Shift+Enter except that it should create a new text block instead

**Comment by nimish-gupta** [comment]
@thangngoc89 can i move forward this issue?

**Comment by thangngoc89** [comment]
Yeah. Sure :D 
So currently , the `Ctrl+Enter` is being registered here https://github.com/Sketch-sh/sketch-sh/blob/2ad9e87e703d72229bcfd9460eb1b75677303eb8/client/src_editor/Editor_Blocks.re#L114-L123 

you need to add another shortcuts there.
As well as adjust `Block_Execute` action to receive an extra field to determine which kind of block it should add

**Comment by thangngoc89** [comment]
Done in #151
