### ISSUE TITLE
Bindings declared on same line are printed in reverse order

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#103]
Example: https://sketch.sh/s/hzq9uKhnC6dwPi8r0T7AyZ/

![screenshot_2018-08-18 wrong order - sketch sh](https://user-images.githubusercontent.com/1830497/44304910-2d0de880-a31f-11e8-8963-7f3a9a525647.png)

**Comment by thangngoc89** [comment]
ah. good call. will fix this asap
