### ISSUE TITLE
Ctrl Clicking or Middle Clicking links does not open them in a new tab

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#104]
For example holding control and clicking Sketch.sh in the top left replaces the current page with the homepage rather than opening the homepage in a new tab. This happens on all other links on the site I can find too.

This happens for me in Firefox, not sure about other browsers.

**Comment by thangngoc89** [comment]
Haha. I'll research on how to handle this gracefully. I'm currently overrding browser's behaviour
