### ISSUE TITLE
Focusing a text or code block prevents editing title

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#105]
Weird bug, if these steps are not clear let me know and I'll add a video.

1. Create a new note
2. Type in some title (works like normal)
3. Click in the code block (no need to type anything)
4. Click in the title
5. Start typing, after the first character focus is moved back to the code block (bug)

It has to do with most recently focused code/text block. If you add a text block, focus it, move focus to the title, then delete the text block, you can edit the title just fine.

On Firefox/Windows, not sure if that is relevant.

**Comment by thangngoc89** [comment]
I know the cause of this. I'll fix it today. thank you for reporting
