### ISSUE TITLE
Allow anonymous editing of all sketches, but not anonymous saving

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#107]
When sending someone a sketch that I have written while logged in, it would be nice if they could edit the variables and mess around with it and see how the code runs and reacts. They should just not be allowed to save those changes since

**Comment by thangngoc89** [comment]
Thank you for suggesting this. This is on high priority list. Should be resolved once fork feature (#70 ) is implemented. There will be no readonly mode

**Comment by thangngoc89** [comment]
On second thoughts, I'm thinking about a **view** mode that you can just play with the code blocks as you like. The markdown content will be rendered into HTML. This would solve the clickable markdown link as well. And paved the way to support more textblock format (rather than just markdown)

**Comment by thangngoc89** [comment]
Done in #145

**Comment by thangngoc89** [comment]
x
