### ISSUE TITLE
Hitting "ctrl-z" after loading an existing sketch deletes all content from focused section

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#112]
1. Write a sketch
2. Save and refresh
3. Focus a text or code block, hit ctrl+z
4. Observe that all text or code is deleted

**Comment by thangngoc89** [comment]
This is definitely annoying. So you expect the content to stay after hitting Ctrl+Z after load right?

**Comment by kyldvs** [comment]
Yeah it should stay, I should only be able to ctrl+z back to the original state I loaded the sketch in, just a minor annoyance I noticed when trying to undo a few things

**Comment by thangngoc89** [comment]
Got it. Thank you for reporting. Little UX details like this is what makes a product great :D

**Comment by thangngoc89** [comment]
So the idea is to clear CodeMirror history after initial set value

We should call `doc.clearHistory()` (search for it in https://codemirror.net/doc/manual.html) after initial setValue here https://github.com/Sketch-sh/sketch-sh/blob/16dec192628a54be0894894ab7558e39c8375389/client/src_editor/Editor_CodeMirror.re#L100
