### ISSUE TITLE
Auto-hide large structures better, or allow manual hiding

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#118]
When a large structure gets printed it can take up many screens without ever getting truncated with an ellipsis anywhere:

https://sketch.sh/s/LhrKjlqGtCDdDyBi0qZWL1/

![screenshot_2018-08-20 buffer deque - sketch sh](https://user-images.githubusercontent.com/1830497/44325881-dd0e4f00-a40e-11e8-89e2-65cbeb4fefa0.png)

**Comment by thangngoc89** [comment]
could yoi give me an example code of large wtructure like that? (just lazy, want to have some code to work on immediately)

**Comment by thangngoc89** [comment]
@ceph3us Wow. That's really interesting. Thank you for the gif.

**Comment by no-stack-dub-sack** [comment]
@thangngoc89 Are you already working on this?

CodeMirror does have collapsible gutter configurations (which you probably have seen), but this obviously wouldn't handle the widgets that show the evaluations. 

If you haven't already started this, I could try to rustle something up

**Comment by thangngoc89** [comment]
@no-stack-dub-sack no. I didn't start to work on this. I don't think collapsible gutter have any effects on line widgets. But if you want to take a look. Please go ahead

**Comment by thangngoc89** [comment]
@no-stack-dub-sack whatever you want to work on.
