### ISSUE TITLE
Show a modal to choose syntax when creating new Sketch

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#122]
Example from Codesandbox
![image](https://user-images.githubusercontent.com/3049054/44349526-6a14df00-a4c7-11e8-89c3-2d7a44d95120.png)

**Comment by kyldvs** [comment]
It would also be cool to be able to reuse different syntaxes within the same sketch, so perhaps choose the syntax per code block.

**Comment by thangngoc89** [comment]
@kyldvs It was added initially in #121 (first commit). But I removed it because:
- There won't be much practical use 
- It complicate the code (like a lot, need to change the storage's model) 
- You can't export it to a valid RE/ML file 

![image](https://user-images.githubusercontent.com/3049054/44352262-0cd05c00-a4ce-11e8-9256-6ee456f04f16.png)

**Comment by kyldvs** [comment]
I would not expect the different languages to interact. My thinking would be that you could then support multiple languages if you wanted, and have some JS code running alongside Reason code.

It does not look ideal though to have that selector on every code section, perhaps you should have to opt into it in the modal by selecting "multiple-languages" or something.
