### ISSUE TITLE
Using polymorphic types breaks auto-indent

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#124]
Type something like the following, then go to the end of line 3 and hit enter. The next line has a large amount of indentation by default. This level of indentations persists even after adding bindings in between throughout the whole document. It makes it very hard to work on the code.

![screenshot_2018-08-20 bad indentation - sketch sh](https://user-images.githubusercontent.com/1830497/44363152-28a91300-a478-11e8-9a79-04f03c38a9e2.png)

**Comment by thangngoc89** [comment]
Ah. This is "smart" indentation of CodeMirror. I'll turn it off

**Comment by thangngoc89** [comment]
Fixed. Should be live in a few minutes (Reload your editor)

**Comment by kyldvs** [comment]
Much better, thank you!
