### ISSUE TITLE
Auto-convert RE to ML to RE when changing languages

### ISSUE THREAD

**Issue by no-stack-dub-sack** [Sketch-sh/sketch-sh#137]
[Reason Tools](https://github.com/reasonml/reason-tools) provides an in-browser converter from RE to ML syntax and back. Wondering if this could be adapted to Sketch so that when you switch from RE to ML, the code is automatically translated to the opposite syntax. 

For the education use-case that Sketch is so great for, this would be incredibly useful for highlighting the differences between Reason and Ocaml and to help promote cross language proficiency between the two.

**Comment by thangngoc89** [comment]
So this requires some changes to 
https://github.com/Sketch-sh/rtop-evaluator to expose refmt for javascript usage. 

Also, what happens when users switch between RE an ML repeatedly? 

Because formatting between 2 syntax creates a mess each time. 


Link issue #18

**Comment by thangngoc89** [comment]
Alright, I exposed refmt for you.

You can see in this file: https://github.com/Sketch-sh/sketch-sh/blob/fc7d82a53a1d536c3e320156685f408ffa64eefd/client/src_editor/Editor_Worker.re#L37-L39

There is 3 new functions:

- reToMl
- mlToRe
- reToRe (this one is used for pretty print Re code).

I think this is pretty much what you needed to make it work. What left is the frontend integration. 
Issues #18 is about pretty print Re code. Could you also work on that as well? (It's pretty much the same code path) 

Thank you very much

**Comment by no-stack-dub-sack** [comment]
@thangngoc89 sure, thanks for the guidance on this! 

I'm thinking maybe a button up by the RE|ML selector that turns auto-convert on/off rather than a confirmation each time. What do you think?

**Comment by thangngoc89** [comment]
@no-stack-dub-sack maybe just ask it 1 time and save the answer to localStorage or something. That button can't accidentally be triggered

**Comment by no-stack-dub-sack** [comment]
@thangngoc89 that sounds good... going to open a WIP PR for this and #18, but it's far from ready. Still dealing with some issues. Will explain in PR thread / IM
