### ISSUE TITLE
Reset store on authentication status change

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#146]
Also update `currentUserId` in EditorNote when authentication change.

This requires upgrading reason-apollo to latest version for this PR https://github.com/apollographql/reason-apollo/pull/125 

And simply call reset store on login/logout

**Comment by idkjs** [comment]
I note the merged tag here. Is this still open?

**Comment by thangngoc89** [comment]
@idkjs good catch, this one is closed :)
