### ISSUE TITLE
The restore deleted block animation is distracting

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#153]
The animation part is really distraction. It basically means I'm not going to be able to continue and work on the sketch for the 10s I wait for it to complete. (Because it's distracting and grabs my attention, not for any other reason)

Can we remove the animation, or add a way to remove the block before the 10s is up?

**Comment by thangngoc89** [comment]
1. I'll make the animation less distracting (completely agree with this lol)
2. How about a remove button? Click on that and the block will be removed immediately

**Comment by kyldvs** [comment]
Both would be great!

**Comment by thangngoc89** [comment]
I would love an PR to do number 2 (a remove button to remove the block immediately) 
It should be in the same row as Restore button

**Comment by thangngoc89** [comment]
Number 1 is done in #165

**Comment by no-stack-dub-sack** [comment]
working on it...
