### ISSUE TITLE
Smarter line widgets add and remove

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#155]
Currently, all line widgets are removed before adding even if they are exactly the same. This leads to an annoying flash and layout thrashing.

We can do better by doing a diff and replace/remove changed widgets

The code section is here:

https://github.com/Sketch-sh/sketch-sh/blob/e27d375ce04703343057269ecb6b74472167aa70/client/src_editor/Editor_CodeBlock.re#L70-L76

**Comment by kyldvs** [comment]
Awesome improvement :) I noticed this a lot

**Comment by thangngoc89** [comment]
@kyldvs in the future, I would like to commit everything in 1 pass. Current, if you have many blocks with large content, it could be annoying
