### ISSUE TITLE
[Looking for ideas] Improving editor experiences

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#158]
Whatever comes out of #147 , we need to improve the editor experiences because currently, it's not so good

# Values/Types output

## Don't display type values right after a type definition

This is just annoying because it's identical
![image](https://user-images.githubusercontent.com/3049054/44915856-5b97b480-ad5e-11e8-971f-6b7de8edac81.png)

Same deal for exception 

![image](https://user-images.githubusercontent.com/3049054/44924666-3dd64980-ad76-11e8-8bcd-e35464ee477c.png)

## ~~Auto collapse long result~~ (#184)

See #118 

## ~~Make value selectable~~ (#185)

Currently, clicking on the value/stdout will put the cursor in the editor instead of selecting value/stdout.
We could have an setting to disable this behavior. and it should not be the default.

**Comment by kyldvs** [comment]
> Make value selectable

I would be careful here, right now it's easy to highlight an entire code block and copy/paste it into an editor. I suspect if you make value/stdout selectable you could accidentally remove the ability to do this.

**Comment by thangngoc89** [comment]
@kyldvs yep. that's why I want to put it behind a setting. (maybe with a shortcut or something). Because sometimes, you really need to select value/stdout

**Comment by kyldvs** [comment]
A button that just pops the raw contents of all code or something into a dialog would be sufficient to make sure people can export things

**Comment by thangngoc89** [comment]
@kyldvs ah. that's even better. thanks for the idea

**Comment by no-stack-dub-sack** [comment]
@kyldvs @thangngoc89 or just a button that copies just the block's code to the clipboard, skipping the dialog. Then values can be selected independently.
