### ISSUE TITLE
Unexpected reset of all the sketch

### ISSUE THREAD

**Issue by fstiffo** [Sketch-sh/sketch-sh#168]
I press SHIFT+CTRL+I to refmt while the page was erasing a code block and all the sketch has been reset to the last saved version.

**Comment by thangngoc89** [comment]
Ah, this is definitely a bug. I'll fix this real quick

**Comment by thangngoc89** [comment]
Hmm what do you mean by last saved version? Like erasing all changes or just restore the queued deleted block?

**Comment by thangngoc89** [comment]
Fixed in #169
