### ISSUE TITLE
Some time the cursor dissapears

### ISSUE THREAD

**Issue by fstiffo** [Sketch-sh/sketch-sh#186]
Some time the blinking cursor disappears, either in code than in text. I'm using Chrome 69.0.3497.81 on W7. Until yesterday the problem had not happen

**Comment by thangngoc89** [comment]
I sometimes see this as well. and AFAIK, I didn't touch the editor code for awhile. So no ideas why is this happening

**Comment by fstiffo** [comment]
It seem not happening more to me.
