### ISSUE TITLE
Deleted blockjs are saved and don't disappear correctly on reload

### ISSUE THREAD

**Issue by matthiaskern** [Sketch-sh/sketch-sh#187]
In my opinion it's undesirable that already deleted sketches are saved.
Also, they don't get hidden correctly on reload.

See: https://sketch.sh/s/UAeFGd3RMKziqvN2VFpBMl/

**Comment by thangngoc89** [comment]
@matthiaskern See https://github.com/Sketch-sh/sketch-sh/issues/149

**Comment by matthiaskern** [comment]
Whoops, I missed that one. Closing in favor of #149
