### ISSUE TITLE
Bug: Elements in reversed order

### ISSUE THREAD

**Issue by joelonsql** [Sketch-sh/sketch-sh#211]
https://sketch.sh/s/hWvJXtqkJvJlGgqenZDfZj/

This code produces different output when comparing a) sketch.sh with b) bsb/node:

a) sketch.sh: "a3 b2 c1"
b) bsb/node: "a1 b2 c3"

**Comment by Drup** [comment]
OCaml bytecode: a3 b2 c1 
OCaml native code: a3 b2 c1

The evaluation order is technically not specified in OCaml and your code relies on the evaluation order in `Seq(annotate(e), annotate(f));`. js_of_ocaml (which sketch uses) and the vanilla compiler seem to agree (although it's not guaranteed either). bs doesn't.

**Comment by Drup** [comment]
On theory, it's unspecified and could thus change. I doubt it will ever change for the mainline compilers. It would break too much code in ways that are too subtle to detect.

**Comment by jordwalke** [comment]
@joelonsql I would encourage you to open a PR or Issue to the bucklescript repo encouraging documentation of this, and/or tweaking the order of evaluation.

**Comment by kyldvs** [comment]
@joelonsql did you happen to delete your sketch? I'm getting a 404 for it now. If so, could you add the example code to this issue for historical context? Not sure what this issue is talking about at this point :)
