### ISSUE TITLE
Unable to save or edit anything

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#219]
I've been unable to save/edit any sketches for around a month. I'm not sure why, maybe I need to re-authenticate with github? But I don't see any way to logout.

![Screenshot_2019-06-19 test - Sketch sh](https://user-images.githubusercontent.com/1830497/59793222-dfd60c80-928a-11e9-8f82-3c5f33beadb7.png)

Each time I save I get a 500 response like this:

```
{"JSON":{"errors":[{"path":"$","error":"postgres query error","code":"postgres-error"}]}}
```

(I have the request that is failing too if that is helpful, but it has some tokens in it that I'm not sure are safe to put here)

**Comment by thangngoc89** [comment]
There was a problem with the database. I fixed and tested it. Please open this issue if things don't work on your end

**Comment by kyldvs** [comment]
It's working now, thanks!
