### ISSUE TITLE
[Enhancement] Create shortcut for adding new code block / text block

### ISSUE THREAD

**Issue by mrvicadai** [Sketch-sh/sketch-sh#221]
## What & Why?

Currently, in order to create a new code / text block, we have to click on the `< > +` or `✎ +` icon. It would be a lot more efficient if we have a simple keyboard shortcut without have to touch the mouse.

**Comment by thangngoc89** [comment]
there are keybindings a tually (Ctrl shift N and Shift N iirc). I working on a much improved version that will remove the concept of blocks entirely. You'll have a blank markdown canvas to work with. Use cut/paste/keyboard shortcuts to move the code around

**Comment by mrvicadai** [comment]
> Ctrl shift N and Shift N iirc
Thanks, I'll give this a try!

> a blank markdown canvas to work with. Use cut/paste/keyboard shortcuts to move the code around
That sounds great -- can't wait to see the new version :)
