### ISSUE TITLE
[V2] Safari crashes on postMessage

### ISSUE THREAD

**Issue by bloodyowl** [Sketch-sh/sketch-sh#226]
Safari requires the second argument, which is the authorised receiver domain. for simplicity, I think that `"*"` can be used here. 

<img width="1121" alt="Screenshot 2019-07-29 at 11 29 48" src="https://user-images.githubusercontent.com/1688645/62037510-31f83f00-b1f4-11e9-964e-453dd6046a41.png">

<img width="1121" alt="Screenshot 2019-07-29 at 11 29 44" src="https://user-images.githubusercontent.com/1688645/62037517-34f32f80-b1f4-11e9-8dc1-d78496d97bcc.png">

**Comment by thangngoc89** [comment]
@bloodyowl thanks for reporting. I didn't know about this.

Would this be enough ? 

```
iframe.contentWindow.postMessage({
    "type": "sketch",
    "payload": message
  }, "*")
```

**Comment by thangngoc89** [comment]
Fixed in https://github.com/Sketch-sh/sketch-sh/commit/5d2f4911ce0140741a140afaee63f8f0875cecce and deployed
