### ISSUE TITLE
Use regex for fast parsing import statement

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#228]
The bundler needs to know all required statements of a particular module before executing it.

Currently, I'm using konan which uses babylon (babel's parser) under the hood. This is really slow for large file (react.js, react-dom) and could freeze the thread for several seconds.

I will move this script to a worker thread later for address the UI responsiness. But in the mean time, I would prefer using a faster way of parsing require statements.

Relevant code:

https://github.com/Sketch-sh/sketch-sh/blob/598839aa67c4414b4439936457bbb6e723dbb026/client/src/container/Container_require_collector.rei#L1

Reference implementation:

https://github.com/facebook/jest/blob/master/packages/jest-haste-map/src/lib/dependencyExtractor.ts#L55-L61

**Comment by tatchi** [comment]
I would be happy to help with this 👍

**Comment by thangngoc89** [comment]
@tatchi awesome 😎. don't hesitate to ask if you have problems navigating the codebase

**Comment by thangngoc89** [comment]
Fixed in #239
