### ISSUE TITLE
[beta.sketch.sh] Dep resolver doesn't work in Safari

### ISSUE THREAD

**Issue by jchavarri** [Sketch-sh/sketch-sh#234]
When opening https://beta.sketch.sh/ in Safari the console shows:

```sh
ApiErrorJson:
Url: https://data.jsdelivr.com/v1/package/resolve/npm/@
{"status":400,"message":"Bad Request. Visit
https://github.com/jsdelivr/data.jsdelivr.com for documentation."}
```

I tracked this down to an issue with how `Url` objects are handled in different browsers. It seems that Safari doesn't put in `url.pathname` the same data as Chrome or Firefox in this line:

https://github.com/Sketch-sh/sketch-sh/blob/d98d0b433d357ea481d1ce191706c26eb2abe026/client/src/container/Container_bundler.re#L92

Small repro: https://codesandbox.io/s/cocky-satoshi-u3kux

**Comment by thangngoc89** [comment]
Fixed in https://github.com/Sketch-sh/sketch-sh/commit/17bad6606bbe3d98995da6f4227ea119944400e4
