### ISSUE TITLE
Move bucklescript's compiler to a worker thread

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#235]
Benefits: 
-  Don't block the main UI thread
- Got **synchronous** function `importScript` to load new stuff into the environment

Consider [promise-worker](https://github.com/nolanlawson/promise-worker/) 's API style which is less verbose and easy to use.

**Comment by thangngoc89** [comment]
Move this to **P/1** . After adding ReasonReact, the response time is pretty terrible, the main thread freezes after each character

Demo:

https://sketch-git-reason-react.sketch-sh.now.sh/

**Comment by thangngoc89** [comment]
![image](https://user-images.githubusercontent.com/3049054/62243618-dc947b80-b407-11e9-89b0-a6f5c4dac7f6.png)

**Comment by jchavarri** [comment]
BuckleScript does not exist anymore and I don't think we will have the resources to build a brand new Sketch engine for ReScript anytime soon, so closing related issues.
