### ISSUE TITLE
Showing compilation error / eval error on the UI 

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#241]
We are current catching error here:

https://github.com/Sketch-sh/sketch-sh/blob/03d7140dbf0e1196d4d6f1994758e6aef8f064b7/client/src/container/Container_bundler.re#L165-L173

`onEntry` for successful compilation and `onError` for error either in compilation or eval step.

# How?

- Add 2 new events to send `to_host` (Comm_eval_error, Comm_eval_entry)

https://github.com/Sketch-sh/sketch-sh/blob/03d7140dbf0e1196d4d6f1994758e6aef8f064b7/client/src/container/Container_comm.re#L7-L9

- Send this event to host on error (something like `Frame_comm.to_host(Comm_eval_error(error))` )

- On host, handle that event here:

https://github.com/Sketch-sh/sketch-sh/blob/03d7140dbf0e1196d4d6f1994758e6aef8f064b7/client/src/pages/edit/Edit_state.re#L147-L169

- On Error, display an overlay on top of the iframe
- On success, remove the error overlay (if any).

**Comment by jchavarri** [comment]
BuckleScript does not exist anymore and I don't think we will have the resources to build a brand new Sketch engine for ReScript anytime soon, so closing related issues.
