### ISSUE TITLE
Recover from fatal error

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#242]
Even though I added catch error pretty much everywhere, the playground can't recover fatal errors.

Reproduce:

```reason
[%%bs.raw {|
  console.log(a);
|}]
```

It should produce a Type error.
Now try to clean it and type in invalid code, it won't be executed.

**Comment by mlms13** [comment]
I noticed this when I accidentally ran a non-tail-recursive endless function, along the lines of:

```reason
let rec recurse = xs => [0, ...recurse(xs)];
```

This pretty quickly blows the stack in the browser, but then deleting it and replacing with `Js.log("a")` doesn't produce any output.

**Comment by thangngoc89** [comment]
@mlms13 yeah. i don't know the root cause of this but that sounds about right

**Comment by thangngoc89** [comment]
Found it, here is the root cause:

https://github.com/frontarm/polestar/blob/d1201ee09b6e3988c98aeb9fddba55e267850583/src/Polestar.ts#L167-L169

I think we are supposed to create a new Polestar instance if error happened
