### ISSUE TITLE
Revert "fix(bs): Show eval error in the hooked console" when #241 is done

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#243]
`fix(bs): Show eval error in the hooked console` https://github.com/Sketch-sh/sketch-sh/pull/231/commits/e983547aad3e9d227faf39632db17ee13368eea6 was added to temporary show the error in the built-in console. Once #241  is done, remember to revert it

**Comment by jchavarri** [comment]
BuckleScript does not exist anymore and I don't think we will have the resources to build a brand new Sketch engine for ReScript anytime soon, so closing related issues.
