### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by robz** [Sketch-sh/sketch-sh#251]
When I attempt to load https://sketch.sh/ I see an error "Invalid SSL certificate"

<img width="1792" alt="Screen Shot 2019-10-27 at 3 54 42 PM" src="https://user-images.githubusercontent.com/1002165/67643222-27704300-f8d2-11e9-889b-56bb2e490e77.png">

**Comment by thangngoc89** [comment]
Thank you for reporting. This was fixed :)
