### ISSUE TITLE
More keymaps to make CodeMirror feels like VSCode

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#26]
Tab : indentMore
Shift-Tab: indentLess

**Comment by alireza-a** [comment]
I think instead of making more like VSCode, we should add key bindings similar to a Jupyter Notebook.
For example
- Shift + Enter: Execture and move to the next block
- Ctrl + Enter: Execute and stay on the same block
- ...

**Comment by thangngoc89** [comment]
@alireza-a I agree with that, do you have an exhaustive list of Jupyter Notebook shortcut?

**Comment by alireza-a** [comment]
Screen shots are taken from [**Jupyter Notebook**'s](https://github.com/jupyter/notebook) `Keyboard shortcuts` section under the `Help` menu option.

I counldn't find a complete documentation of the commands except in the Help menu of the notebook itself. So I extracted the key bindings out by running,

```js
Jupyter.keyboard_manager.command_shortcuts.help().map(e => {
    return `${e.shortcut} --> ${e.help}`
}).join("\n")
```

In the dev console when running a local version of `Jupyter Server`.

```
f --> find and replace
enter --> enter edit mode
meta-shift-f --> open the command palette
meta-shift-p --> open the command palette
p --> open the command palette
shift-enter --> run cell, select below
ctrl-enter --> run selected cells
alt-enter --> run cell and insert below
y --> change cell to code
m --> change cell to markdown
r --> change cell to raw
1 --> change cell to heading 1
2 --> change cell to heading 2
3 --> change cell to heading 3
4 --> change cell to heading 4
5 --> change cell to heading 5
6 --> change cell to heading 6
k --> select cell above
up --> select cell above
down --> select cell below
j --> select cell below
shift-k --> extend selected cells above
shift-up --> extend selected cells above
shift-down --> extend selected cells below
shift-j --> extend selected cells below
a --> insert cell above
b --> insert cell below
x --> cut selected cells
c --> copy selected cells
shift-v --> paste cells above
v --> paste cells below
z --> undo cell deletion
d,d --> delete selected cells
shift-m --> merge selected cells, or current cell with cell below if only one cell is selected
meta-s --> Save and Checkpoint
s --> Save and Checkpoint
l --> toggle line numbers
o --> toggle output of selected cells
shift-o --> toggle output scrolling of selected cells
h --> show keyboard shortcuts
i,i --> interrupt the kernel
0,0 --> restart the kernel (with dialog)
esc --> close the pager
q --> close the pager
shift --> ignore
shift-l --> toggles line numbers in all cells, and persist the setting
shift-space --> scroll notebook up
space --> scroll notebook down
```

<img width="690" alt="screen shot 2018-08-13 at 11 51 57 pm" src="https://user-images.githubusercontent.com/15719232/44070858-24a5094a-9f54-11e8-89e1-c5478e80cedc.png">

<img width="691" alt="screen shot 2018-08-13 at 11 52 09 pm" src="https://user-images.githubusercontent.com/15719232/44070861-2646b05a-9f54-11e8-99da-b6c63a8f1880.png">

**Comment by thangngoc89** [comment]
Alright. I will implement Shift+Enter and Crtl +Enter first. should be easy

**Comment by thangngoc89** [comment]
@alireza-a for shift-enter and ctrl+enter shortcut, do I have to focus in the block/celll for it to works?

**Comment by alireza-a** [comment]
I think when you open the notebook the first cell gets selected.
In our case since a Sketch will always have a at least one cell, we do the same and when you open a Sketch select the first cell.

**Comment by thangngoc89** [comment]
@alireza-a Thank you for the information. I should find a demo of Jupyter and play with it. I already implemented a global shortcut system here https://github.com/Sketch-sh/sketch-sh/pull/95 
So adding the shortcuts shouldn't be hard

**Comment by alireza-a** [comment]
- `Ctrl-Enter`: Executes the focused block, and continues focusing on it.
- `Shift-Enter`: Executes the focused block and focuses on the next block. If there is no next block it creates a new block and focus on it.

**Comment by thangngoc89** [comment]
@alireza-a Got it. I just try it with a live Jupyter instance
