### ISSUE TITLE
Bug: Can't get an overview of my all my own sketches

### ISSUE THREAD

**Issue by marcoemrich** [Sketch-sh/sketch-sh#269]
If I click on my avatar (url: https://sketch.sh/u/marcoemrich), to see all my sketches, I get an error message instead:

```
marcoemrich's sketches
GraphQL error: field "owner" not found in type: 'note_bool_exp'
```

![image](https://user-images.githubusercontent.com/447570/97248426-123e3500-1802-11eb-88d3-009997926011.png)

**Comment by fstiffo** [comment]
The same error for me. 
![image](https://user-images.githubusercontent.com/3993564/97542826-b58c7700-19c7-11eb-87cc-f0db8c926a01.png)

**Comment by thangngoc89** [comment]
Hmm. Thank you for reporting this. I will take a look. Not sure why it's suddenly stopped working

**Comment by shubhamgupta731** [comment]
Same here for me

**Comment by thangngoc89** [comment]
Sorry guys 😓. Sketch really needs a revamp of its backend. It designed Sketch’s backend when I was really hyped about microservices, docker and everything. Now they are starting to break apart
