### ISSUE TITLE
Sketch is down?

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#272]
The entire site seems broken for me. Right now it dumps me into a directory structure that lets me look at the docs, and links like https://sketch.sh/new/reason are a 404.

**Comment by bluddy** [comment]
The root site seems to be up, but subdirectories don't seem to direct properly.

**Comment by idkjs** [comment]
[Phantom Types in ReasonML](https://sketch.sh/s/nerP3hkOxX6sMVvVUtBIbs/) by Ali Sharif

**Comment by thangngoc89** [comment]
Everything is up and running now. Sorry for the interruption

**Comment by kyldvs** [comment]
Thanks for fixing things up :)
