### ISSUE TITLE
Existing Sketches are not found any more (404)

### ISSUE THREAD

**Issue by marcoemrich** [Sketch-sh/sketch-sh#277]
For example: https://sketch.sh/s/e9MlLetFJNLVbEJ6J99NBR/

**Comment by idkjs** [comment]
[Phantom Types in ReasonML](https://sketch.sh/s/nerP3hkOxX6sMVvVUtBIbs/) by Ali Sharif

**Comment by thangngoc89** [comment]
It works now. Thank you very much
