### ISSUE TITLE
Github login not working

### ISSUE THREAD

**Issue by maiksensi** [Sketch-sh/sketch-sh#278]
Hey hey, when I try to login via github I get an error: 

![image](https://user-images.githubusercontent.com/6359386/104935351-6a24ac00-59ab-11eb-8e8d-bfa638d3b8d6.png)

let me know if I can help with further information.

**Comment by vrmiguel** [comment]
Same thing happening here

**Comment by thangngoc89** [comment]
It works now. Thank you very much
