### ISSUE TITLE
Make markdown links clickable

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#30]
Use `doc.markText` to replace the link with another node with `replaceWith` option. Next thing is to figure out how to find the links

**Comment by Haroenv** [comment]
I looked a bit into it, and it's not very easy

```js
document.querySelectorAll(".CodeMirror .cm-link").forEach(el =>
  el.addEventListener("click", e => {
    const shouldOpen = e.metaKey || e.ctrlKey;
    const link = e.target.nextSibling;
    if (shouldOpen && link.classList.contains("cm-url")) {
      const href = link.innerText.replace(/[()]/g, "");
      window.open(href);
    }
  })
);
```

Note that this works, but only when the text is already written (all events need to be removed and added when DOM changes 😢), as well as it won't work with links that aren't adjacent or inline. But it's something. 

found inspiration [here](https://discuss.codemirror.net/t/clickable-urls-in-markdown-mode/1389)

**Comment by thangngoc89** [comment]
@Haroenv Ah. This is great ! Thank you for the pointer. I see that HyperMD have clickable markdown link https://laobubu.net/HyperMD/#README.md but didn't have time to check it out.

**Comment by Haroenv** [comment]
I think their trick might be with turning it into html first ([with `marked`](https://github.com/laobubu/HyperMD/blob/a0241fbe251c194b501635bda01596090a9cc9c8/src/powerpack/hover-with-marked.ts)), which then allows them to link, or it might also have something to do with this code: 

https://github.com/laobubu/HyperMD/blob/7bdeb397ba56d944c9290fbda8a32869e7cc3dfb/src/mode/hypermd.ts#L304

but I didn't investigate any further yet

**Comment by Haroenv** [comment]
Actually, the code is more likely [here](https://github.com/laobubu/HyperMD/blob/c8d4387b149bff2cc29f8be53792ce814239c17d/src/addon/click.ts#L31), since they use the alt key for opening in new tab (which should be ctrl / cmd IMO)

**Comment by thangngoc89** [comment]
@Haroenv Thank you for investigating this. I will check this out the next days. This is a commonly ask feature :)

**Comment by thangngoc89** [comment]
Another method here:

https://stackoverflow.com/questions/26933344/codemirror-detect-and-create-links-inside-editor

**Comment by thangngoc89** [comment]
#152 introduced a hack for displaying link handle on mouse hover. It's ugly and not mobile friendly. Will keep investigating this further in another iteration

**Comment by Haroenv** [comment]
How are you supposed to use the hack 🤔 the handle disappears when you move towards it

**Comment by thangngoc89** [comment]
I agree that it sucks ! But it doesn't work for you? 
![ezgif-1-3432c154fa](https://user-images.githubusercontent.com/3049054/44806518-64b74300-abf1-11e8-8a32-b4b89c0c6a3a.gif)

**Comment by thangngoc89** [comment]
Oh. Thank you for letting me know. I'll look into improve this hack for safari. This is not cool

**Comment by Haroenv** [comment]
Maybe it would be interesting if you could have that icon always visible?

**Comment by thangngoc89** [comment]
@Haroenv yes. That's what I want to do. I updated the issue first post. `doc.markText` method could renders what I want. But I'm not sure how to capture links
