### ISSUE TITLE
Maybe we could use a better authorization name?

### ISSUE THREAD

**Issue by maxlibin** [Sketch-sh/sketch-sh#312]
Authorize @jchavarri  :D

![Screenshot 2022-01-07 at 2 47 24 PM](https://user-images.githubusercontent.com/1277038/148503577-74274b83-275c-47ee-8d87-a457e2be4fb6.png)

**Comment by jchavarri** [comment]
This is fixed now, the app belongs to ahrefs org now.

<img width="621" alt="imagen" src="https://user-images.githubusercontent.com/220424/152544196-9b6ccf9f-3cd1-4e28-bed8-f1d47a9a4894.png">
