### ISSUE TITLE
Is sketch.sh down for everyone?

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#346]
For some reasons, the auto renew function of namecheap didn’t work as expected. Luckily I renewed the domain manually just in time.
But it’s showing namecheap’s domain parking page instead.

![1AF09C0E-1801-4613-ABE5-E1A03A430BBA](https://user-images.githubusercontent.com/3049054/184493009-4a939695-2cb5-4f13-b7cd-c2d6729166fe.png)

is it just me or for everyone?

**Comment by Khady** [comment]
Maybe it took a few minutes to restore the dns? It seems to be fine on my side right now.

![694771BD-794B-484E-A8DE-EFB1B1B7BD36](https://user-images.githubusercontent.com/974142/184494403-09f8a2b8-45d4-4c94-a4a6-714fe89a6aa0.png)

**Comment by thangngoc89** [comment]
You’re right. It’s working as expected on my end as well. Seems like a problem with slow dns propagation.
