### ISSUE TITLE
Add ability to reorder blocks

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#38]
Right now if you have a code block then a text block, it's not easy to move the text block above the code without copy/pasting the content. Would be nice to have a move up/down button to control the blocks.

**Comment by thangngoc89** [comment]
I think we can start with adding move block up and down buttons. (on visible on hover).
Drag and drop to reorder would complicate things a lot (but if you can do it, please go ahead)

**Comment by jordwalke** [comment]
Here's [another feature](https://github.com/Sketch-sh/sketch-sh/issues/98) I've requested which I think would at least provide an easier way to do these larger rearrangements.
