### ISSUE TITLE
Add timelimit or cancel button for executing code to recover from infinite loops

### ISSUE THREAD

**Issue by kyldvs** [Sketch-sh/sketch-sh#39]
If you write something like:

```
let x = 1;
while (true) {};
```

Anything else you add after, even after removing the infinite loop, will not be run

(it doesn't crash the tab or anything all that bad though!)

**Comment by thangngoc89** [comment]
oh yeah. this is really something I want to prevent. thank you for the suggestion

**Comment by thangngoc89** [comment]
So after doing some research, there is no way to stop toplevel from executing a code, but we can just terminal a web worker.

```
Promise.race([
  executeCode(),
  terminalWorker()
])
```

Currently blocked by #45
