### ISSUE TITLE
Prebuild docker images with bs-platform

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#67]
Pretty much a new docker image with the first 3 lines of current Dockerfile for frontend building 

https://github.com/thangngoc89/rtop-ui/blob/9bdf5b413d9cb04e164440189178cb55b5da6b5b/Dockerfile#L1-L3

This would help speeding up now.sh build speed

**Comment by matthiaskern** [comment]
This could also include cypress, or be based on one of https://github.com/cypress-io/cypress-docker-images.

**Comment by thangngoc89** [comment]
@matthiaskern I'm currently not running cypress on now. Because setting the whole thing up is complicated in a single docker file. That image is prebuilt with some packages like xbvf ,... that's neccessarry for UI based testing

**Comment by thangngoc89** [comment]
Done in #127
