### ISSUE TITLE
Add ability to delete a sketch

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#94]

**Comment by fstiffo** [comment]
Could be useful non only for the space but also for the indexing

**Comment by thangngoc89** [comment]
@fstiffo what do you mean by indexing?

**Comment by fstiffo** [comment]
google indexing

**Comment by acoll** [comment]
Should the delete remove all the data related to the note or just update a `deleted` boolean flag on the record?

**Comment by kyldvs** [comment]
I think it should add a deleted boolean, and hide it from your list of notes/display a notice or something. Perhaps some other restrictions like no running/forking. I don't like the idea of the note getting deleted and lost by accident.

**Comment by acoll** [comment]
That was my initial thought too. I went ahead with an actual deletion only because it looked pretty easy and because @fstiffo  mentioned something about space (I assumed they meant disk).

**Comment by matthiaskern** [comment]
Closed via #202
