### ISSUE TITLE
[Proposal] Remove url encoded feature

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#97]
URL encoded feature is added with a vision that sketch links won't be useless if the service is down or even if sketch.sh is discontinue. It is really a nice feature because I was tired of non-working jsfiddle links on Stackoverflow. 

But as folks are using sketch.sh for writing [micro][1] [blogs][2] and really long code, more problem arise with this feature:

[1]: https://sketch.sh/s/YbsjH3Jsnd0yaKwvyKhQzC/
[2]: https://sketch.sh/s/F8s8tCTWhsXgxcExxLHHdB/

See #92 . A user lost an hour of work because it can't save the sketch. Heroku router drops requests with headers larger than 8KB combined.

I attempted to fix it by using a proxy to drop referer header in #96 . But after stress testing it, [it didn't work](https://github.com/Sketch-sh/sketch-sh/pull/96#issuecomment-413949019) 

> For reproduce case, you can go to https://staging.sketch.sh/s/6AoXUxgS7OTfblLZYLqyw2
> wait for url to turn into the long form. Refresh the page. It will just not connecting.
> I'm not sure if this a limitation of server or browser or both but really tired of solving this problem

Also, Discord has a hard limitation of 2000 characters so sometime, you can't easily paste a sketch link into it.

I've spent a considerable amount of time fixing the issues around url encoded feature. And in the end, I don't think it worths the effort. Don't get me wrong, the feature is extremely useful, but not practical.

So I'm writing this proposal for dropping url encoded feature. Please express your opinions/comments.

**Comment by thangngoc89** [comment]
cc @ceph3us @kyldvs

**Comment by kyldvs** [comment]
I would support removing this feature. I think this is a really nice platform for writing longer notes/tutorials/blogs. It would not be ideal if that weren't possible because of the limit restrictions on URLs

**Comment by jordwalke** [comment]
I like that with TryFlow, I can create examples and share them with people, without needing an account or signing in. I think I would share far fewer TryFlow examples if I had to have an account or sign in.

Would the following make sense:
- If not signed in, save links by encoding the URL (and warn if the length is > the threshold amount of bytes)
- If signed in create short links.

Fore more permanence it would be cool to have an export/import feature. Imagine importing a standard markdown file where ` ```reason ` tags become the runnable examples.

**Comment by thangngoc89** [comment]
@jordwalke Thank you for your input. Currently, you are not required to sign in to create sketches. You can even edit your sketches anonymously. I would say that handling things differently between signed in and not signed in would complicating the code significantly

As for export/import feature, there is already an issue for it here #41

**Comment by grsabreu** [comment]
I agree with @kyldvs

**Comment by ceph3us** [comment]
As a short code playground, direct encoding makes sense. But if it's being used for literate programming the technical restrictions obviously make it preferable not to do this. I would at least advocate an auto saving to gist feature though, since GitHub sign in is already implemented.

**Comment by thangngoc89** [comment]
Thank you @kyldvs @grsabreu @ceph3us for your inputs
As of saving to gist, I think it's totally possible to do it client-side. I created #99 to track this feature

**Comment by jdeisenberg** [comment]
Instead of a URL encode, is it possible to implement "download source"?

**Comment by thangngoc89** [comment]
@jdeisenberg Yes. Totally possible see #41 . But download source doesn't solve the broken links problem (which is what url encode trying to solve)

**Comment by thangngoc89** [comment]
Thank you all for your input. I'll will remove the url encoded feature and will continue to work to improve sketch.sh
