### ISSUE TITLE
Ability to import / export plain .md

### ISSUE THREAD

**Issue by jordwalke** [Sketch-sh/sketch-sh#98]
Another approach to permanence, would be to have an export/import feature. Imagine importing a standard markdown file where ` ```reason ` tags become the runnable example code blocks.

` ```reason-norun ` could become blocks embedded as code that doesn't become a runnable block, but instead is only syntax highlighted.

**Comment by thangngoc89** [comment]
Ah. I already documenting this feature via #41 but it seems like your format for markdown is cleaner

**Comment by jordwalke** [comment]
I'll close this one.
