### ISSUE TITLE
Autosaving to gist 

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#99]
From https://github.com/Sketch-sh/sketch-sh/issues/97#issuecomment-413959839 

I believe we can do this completely on client-side

**Comment by jordwalke** [comment]
One downside is that it requires requesting access to *all* the users' gists (I believe) instead of just write access, which is a pretty broad permission to ask for something that doesn't even need to read any gists.

**Comment by ceph3us** [comment]
Yes, there's no granular scope for public only Gist write access. You either get read and write access to a user's public and private gists with the `gist` scope, or you get no write access at all. This has implications for client and server side too - the server would have to be trusted to not lose or misuse OAuth2 tokens, and client side login may leave the token vulnerable on user's devices.

**Comment by thangngoc89** [comment]
currently, token is saved on server, it's never saved on user's devices
